---
- name: Install nginx
  hosts: web
  become: true
  tasks:
    - name: Update the apt-get
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: "nginx"
        state: present

    - name: Create a directory if it does not exist
      file:
        path: "{{ website_path_nginx }}"
        state: directory

    - name: Copy new temple file index.html.j2 file
      template:
        src: "index.html.j2"
        dest: "{{ website_path_nginx }}/index.html"

    - name: Copy configuration file for nginx
      copy:
        src: "sudha.conf"
        dest: "/etc/nginx/sites-available/sudha.conf"

    - name: reStart nginx
      service:
        name: nginx
        state: restarted